#!/bin/bash
ROOTFS_PATH=/export/rootfs
LOADADDR=0x82000000
INSTALL_IMAGE_PATH=${ROOTFS_PATH}/boot
INSTALL_MOD_PATH=${ROOTFS_PATH}
INSTALL_FW_PATH=${ROOTFS_PATH}/lib/firmware

make INSTALL_PATH=${INSTALL_IMAGE_PATH} INSTALL_MOD_PATH=${INSTALL_MOD_PATH} INSTALL_FW_PATH=${INSTALL_FW_PATH} \
    LOADADDR=${LOADADDR} ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- $@
